services:
  _defaults:
    autowire: true
    autoconfigure: true

  Symfinity\PrivacySettingsBundle\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/PrivacySettingsBundle.php'
      - '../src/Controller/'

  Symfinity\PrivacySettingsBundle\Controller\ConsentSubmitController:
    tags: ['controller.service_arguments']

  Symfinity\PrivacySettingsBundle\Consent\PreferenceStoreInterface:
    alias: Symfinity\PrivacySettingsBundle\Consent\SessionPreferenceStore
